# Generated by Django 5.0.3 on 2024-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("To_Do_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
